### ISSUE TITLE
API - sending raw data by indexation messages.

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/iota.c#131]
## Description

Sending raw/hex data via `send_indexation_msg` causes incorrect data payload in the message.

## Motivation

send_indexation_msg can take both string data and hex data for flexibility.

## Open questions (optional)

Should we create a new API, say `send_hex_indexation_msg`, or add a new parameter in `send_indexation_msg`?

**Comment by H-saerdnA** [comment]
[iota_c_test_01.zip](https://github.com/iotaledger/iota.c/files/6444740/iota_c_test_01.zip)

Hello,

this is a test to send encrypted data with send_indexation_msg. 

Uncomment the #define D_GOOD_MESSAGE and the decryption of the Message will fail because the encrypted Message was not send compete to the Tangle.

I hope the Code is correct and let me know if i can do something.

Andreas H.

**Comment by H-saerdnA** [comment]
Hello,

this is a test to send encrypted data with send_indexation_msg.

Uncomment the #define D_GOOD_MESSAGE and the decryption of the Message will fail because the encrypted Message was not send compete to the Tangle.

I hope the Code is correct and let me know if i can do something.

Andreas H.
[iota_c_test_01.zip](https://github.com/iotaledger/iota.c/files/6444793/iota_c_test_01.zip)

**Comment by oopsmonk** [comment]
@H-saerdnA `send_core_message` is able sending out encripted data instead of `send_indexation_msg`.

**error handlings are ignored in the following examples**

1. send binary data to the Tangle
```c
indexation_t* idx = NULL;
core_message_t* msg = NULL;
res_send_message_t msg_res = {};
// create a indexation payload
idx = indexation_create(s_index, s_encrypted_ptr, encrypted_len);
// create a message object 
msg = core_message_new();
// make it become an indexation message
msg->payload = idx;
msg->payload_type = 2; // the type of indexation playload 
// send the message
send_core_message(&client_endpoint_cfg, msg, &msg_res);
```

2. decode data from `get_message_by_id`
```c
byte_buf_t *payload_encrypted_ptr;
payload_index_t *payload_index_t_ptr;
size_t received_payload_len;

payload_index_t_ptr = response_message_data.u.msg->payload;
// a hex string of indexaction data
payload_encrypted_ptr = payload_index_t_ptr->data;
// convert hex string to binary
byte_t data_bin[1024];
hex2bin(payload_encrypted_ptr->data, payload_encrypted_ptr->len, data_bin, payload_encrypted_ptr->len/2);

// data_bin should equal to original encrypted data(s_encrypted_ptr)
int ret = memcmp(s_encrypted_ptr, data_bin, encrypted_len);

message_len = (payload_encrypted_ptr->len/2) - crypto_secretbox_MACBYTES;
s_decrypted_ptr = (char *) malloc ( message_len + 1 );

rc = crypto_secretbox_open_easy ( s_decrypted_ptr, data_bin, payload_encrypted_ptr->len/2, nonce, key );
s_decrypted_ptr[message_len] = '\0';
printf ( "Decrypted Received Message = \"%s\"\n\n", s_decrypted_ptr  );
free ( s_decrypted_ptr );
```

outputs are shown below
```
Message to encrypt = "{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message" }"

Check Decrypted Message = "{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message" }"

The length of the encrypted string is 207.
[main:141] message ID: 98846e0c1634cad69c2ef8cbe4e4e3690b4e8b7b37b35b6ce77af3e02933f90c
Decrypted Received Message = "{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message"{ Hello this is a "Message" }"
```

**Comment by H-saerdnA** [comment]
@oopsmonk 
I have changed now from send_indexation_msg to send_core_message for sending encrypted payloads. It all works well.

I think it is not nessesary to modify send_indexation_msg.

Many thanks :-)

**Comment by oopsmonk** [comment]
@H-saerdnA thanks for your feedback, I will add an example of sending binary data.

**Comment by oopsmonk** [comment]
added an example at d1762dfb932d5291ba33878be24e74ee05acae79
