### ISSUE TITLE
Get Node Info: extra stuff

### ISSUE THREAD

**Issue by SiliconDroid** [iotaledger/iota.c#132]
It would be nice to have the other available data members in struct **get_node_info_t**:

float messagesPerSecond
float referencedMessagesPerSecond
float referencedRate
uint64_t latestMilestoneTimestamp

**Comment by oopsmonk** [comment]
fixed at https://github.com/iotaledger/iota.c/commit/87d8f1ac7062a40dc31194729c4517412ac11fde

**Comment by SiliconDroid** [comment]
Awesome!
