### ISSUE TITLE
Address calculation...

### ISSUE THREAD

**Issue by SiliconDroid** [iotaledger/iota.c#133]
To be compliant with firefly, the wallets seed byte count needs doubling from 32 bytes to 64 bytes.

FILE:
iota_client\src\core\seed.h 

CHANGE:
#define IOTA_SEED_BYTES (ED_SEED_BYTES * 2)

after this change I am able to produce addresses the same as firefly.

<details>
<summary>click here for good test vectors</summary>

I am using mbedtls_pkcs5_pbkdf2_hmac to derive seed hex from word list but you can just test this using seed hex as input.

**WORD LIST:**
"affair dream proof disagree human bind tell shield camera buffalo voyage endless feed sister glimpse thing fantasy upon claw want sketch level december media"

**SEED HEX (512 bit entropy):**
c925cfc7c853d5319a2feab704e5efa1e13e98e45cf8d2cb91e718a5f39ec342c33f9d042e17dba43bb3e5e011743a1be004528f2be776210d8c609100e7edbe

**PATH:**
"m/44'/4218'/0'/0'/0'"

**ADDRESS[0] HEX:**
009f0bbafe9016a2e75ae4a564e9511f73b91896b44d29c484daf223801709cf7d

**ADDRESS[0] BECH32:**
atoi1qz0shwh7jqt29e66ujjkf623raemjxykk3xjn3yymtez8qqhp88h6x63z4j
</details>

**Comment by oopsmonk** [comment]
`IOTA_SEED_BYTES` represents the seed in binary form(32 bytes) which is specified in RFC.
iota.c is a client library for general purposes.
For a hex-encoded seed that is widely used in applications, it should add `IOTA_SEED_HEX_BYTES` and keep `IOTA_SEED_BYTES`.
`#define IOTA_SEED_HEX_BYTES (IOTA_SEED_BYTES*2)`
imo, it's an enhancement for flexibility, not a bug :)

**Comment by oopsmonk** [comment]
added `IOTA_SEED_HEX_BYTES` at https://github.com/iotaledger/iota.c/commit/cdba2c58f1c1a96a28c30ab94fd02208362f1bf1
