### ISSUE TITLE
Index length

### ISSUE THREAD

**Issue by apalmieriGH** [iotaledger/iota.c#139]
Since an Index can be maximum 64 UTF-8 chars or maximum 128 hex chars, shouldn't the array declared at
https://github.com/iotaledger/iota.c/blob/a6bb6f39628102b94edc381724c2f092e918ef17/src/client/api/v1/find_message.c#L135

be replaced by:
`char index_hex[129] = {};`

and the check at
https://github.com/iotaledger/iota.c/blob/a6bb6f39628102b94edc381724c2f092e918ef17/src/client/api/v1/find_message.c#L142

replaced by:
`if (index_str_len > 64)` ?

**Comment by oopsmonk** [comment]
The maximum of Index is 64 bytes which can be 128 bytes hex string  or 64 bytes string literals. 
A UTF-8 character could be 1 to 4 bytes.

**Comment by apalmieriGH** [comment]
Maybe this advise in the [Tangle Explorer](https://explorer.iota.org/testnet) is a bit misleading...
![Index](https://user-images.githubusercontent.com/14570650/126954623-ca25ae1a-09fd-4e82-9dce-510574095a8d.png)

**Comment by oopsmonk** [comment]
fixed in https://github.com/iotaledger/iota.c/commit/bbb38f6b4ea040f85c4eae265827449fb432779f
