### ISSUE TITLE
Make iota.c build on MSVC

### ISSUE THREAD

**Issue by MatthewDarnell** [iotaledger/iota.c#14]
Hi,

I'm working on building iota.c as an `ExternalProject` in CMake under MSVC (using CLion ide)

I'm having some trouble getting it to build correctly, namely in 2 spots:

`embear_logger/src/ext_embear_logger/src/logger.c` :

This file contains `#include <unistd.h>` which is not available in MSVC. 

Can this be edited to something like: 

```
#ifdef WIN32
 #include <winsock2.h>
#else
 #include <unistd.h>
#endif
``` 

?

Also, in `common/model/transfer.c`:

```
  tryte_t trytes_msg[trytes_len];
  ascii_to_trytes(str, trytes_msg);
  return transfer_message_set_trytes(tf, trytes_msg, trytes_len);
```

But I'm getting an error about defining a variable-length array on the stack.

Can we add a workaround for win32 to malloc this?

Perhaps:

```
tryte_t *trytes_msg = (tryte_t*)calloc(sizeof(tryte_t), trytes_len);
ascii_to_trytes(str, trytes_msg);
retcode_t retVal = transfer_message_set_trytes(tf, trytes_msg, trytes_len);
free(trytes_msg);
return retVal;
```

My CMake skills aren't the best, and I haven't been able to build it successfully yet on windows because these files aren't generated until after it starts the build process, then it fails before I can edit the files, so there may be more areas to edit.

**Comment by oopsmonk** [comment]
Hey, Matthew as you see some external libraries are not able to compile through MSVC. We have libraries in different languages like iota.js, iota.py,  iota-java...etc, iota.c follows POSIX standards and is designed for embedded devices. For Windows I suggest to use mingw-gcc but iota.c is not tested on Windows currently.

**Comment by MatthewDarnell** [comment]
MSVS log:

```
Scanning dependencies of target logger
[ 50%] Building C object src/CMakeFiles/logger.dir/logger.c.obj
cl : Command line warning D9002 : ignoring unknown option '-g'
cl : Command line warning D9002 : ignoring unknown option '-pedantic'
cl : Command line warning D9002 : ignoring unknown option '-std=c99'
C:\Users\matth\CLionProjects\iota-simplewallet\cmake-build-debug\iota.c-prefix\src\iota.c-build\_deps\iota_common-build\embear_logger\src\ext_embear_logger\src\logger.c(20): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx86\x86\cl.exe' : return code '0x2'
```


And then I also tried MinGW, but it failed at a different step. (`cmd.exe \c mklink \j <link> <target>`):

```
[100%] Built target unity
-- Could NOT find Perl (missing: PERL_EXECUTABLE)
-- Configuring incomplete, errors occurred!
See also "C:/Users/matth/CLionProjects/iota-simplewallet/cmake-build-debug/iota.c-prefix/src/iota.c-build/mbedtls/src/ext_mbedtls-build/CMakeFiles/CMakeOutput.log".
CMake Error at CMakeLists.txt:110 (message):
  Could not create symbolic link for:
  C:/Users/matth/CLionProjects/iota-simplewallet/cmake-build-debug/iota.c-prefix/src/iota.c-build/mbedtls/src/ext_mbedtls/include/mbedtls
  --> Invalid switch - "Users".
```

**Comment by MatthewDarnell** [comment]
I realized the problem with MinGW. CMake has trouble creating symlinks on Windows.(https://gitlab.kitware.com/cmake/cmake/issues/17739)

The mbedtls symlink directories not already existing, which CMake seems to not be able to detect and therefore fails, (see kitware issue 17739 linked above)

I was able to build iota.c on MinGW by doing the following:

```
if(WIN32)
  file(MAKE_DIRECTORY "${CMAKE_SOURCE_DIR}/cmake-build-debug/iota.c-prefix/src/iota.c-build/mbedtls/src/ext_mbedtls-build/include/mbedtls")
  file(MAKE_DIRECTORY "${CMAKE_SOURCE_DIR}/cmake-build-debug/iota.c-prefix/src/iota.c-build/mbedtls/src/ext_mbedtls-build/scripts")
endif(WIN32)

ExternalProject_Add(iota.c
  GIT_REPOSITORY https://github.com/iotaledger/iota.c
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_SOURCE_DIR}/iota.c
)
```

This will create the 2 directories to be linked, and CMake successfully built iota.c on MinGW.

**Comment by oopsmonk** [comment]
> And then I also tried MinGW, but it failed at a different step. (`cmd.exe \c mklink \j <link> <target>`):

You need MSYS2 or Cygwin for building POSIX-compliant applications on Windows. 
`MAKE_DIRECTORY` is deprecated and should have no this issue on MSYS2.
