### ISSUE TITLE
Memory Leak in ​Function send_core_message calling byte_buf_free(json_data)

### ISSUE THREAD

**Issue by H-saerdnA** [iotaledger/iota.c#141]
## Bug description

The data-Member of json_data is provided by cJSON_PrintUnformatted:

`char* msg_str = message_to_json(msg);`
`...`
` json_data->data = (byte_t*)msg_str;`

 

Should it be freed with cJSON_free  instead of byte_buf_free ?

`#ifdef __IOTA_C_OLD__`
`  byte_buf_free(json_data);`
`#else`
`  cJSON_free(msg_str);`
`#endif`

## Version

v0.2.0

- Version:

## IOTA network

Which node are you connected to and which IOTA network is it in?

- Node URL:
- Network:

## Hardware specification

What hardware are you using?

- Operating system: Windows

## Compiler and build tool specification

Microsoft Visual Studio

**Comment by oopsmonk** [comment]
https://github.com/DaveGamble/cJSON#printing-json
> It will allocate a string and print a JSON representation of the tree into it. Once it returns, you are fully responsible for deallocating it after use with your allocator. (usually free, depends on what has been set with cJSON_InitHooks).

in this case, it can be freed via `byte_buf_free` or `cJSON_free`,  how did you get memory leaks from `byte_buf_free`?

**Comment by H-saerdnA** [comment]
Hi,
thank you for the link. I have to read something ;-)


I am trying to build iota.c with Microsoft Visual Studio. All Libraries (libsodium, cJson etc.) that will be used, i have created with vcpkg.

When I send a Message using send_core_message the Program stopped here:

![screeenshot](https://user-images.githubusercontent.com/83837586/129179357-f1f6010c-da74-45e0-9b1a-568a53690dc6.jpg)

**Comment by oopsmonk** [comment]
it doesn't mean a memory leak but could be a double free. 
the problem is iota.c doesn't support MSVC compiler at the moment, see https://github.com/iotaledger/iota.c#prerequisites
I recommend using GCC from [msys2](https://www.msys2.org/) or [mingw](http://mingw-w64.org/doku.php) but a PR for MSVC support is welcome.

**Comment by H-saerdnA** [comment]
OK, I'll analyze that further.

At the Moment the IOTA.c-Library, compiled with MSVC, is working well for me, but I have to do some  Adjustments like:

`res_message_t *msg = malloc(sizeof(res_message_t));`
in
`res_message_t *msg = (res_message_t *) malloc(sizeof(res_message_t));`

MSVC said it cannot convert `void *` in `res_message_t *`.

Or

`#ifdef _MSC_VER`
` `
`   http_client_config_t http_conf;`
`    memset(&http_conf, 0, sizeof( http_client_config_t ));`
`    http_conf.host = ctx->host;`
`    http_conf.path = cmd->buf;`
`  http_conf.use_tls = ctx->use_tls;`
`  http_conf.port = ctx->port;`
` `
`#else`
`  http_client_config_t http_conf = {.host = ctx->host, .path = cmd->buf, .use_tls = ctx->use_tls, .port = ctx->port};`
` `
`#endif`

Here MSVC said that ther is as Syntaxerror "." in:

`http_conf = { .host`


Unfortunately I don't know why the MSVC compiler has problems with these Peaces of the source code. I think there is somewhere an option that I have set wrong. Here I need Support ;-)


But doing these Adjustments MSVC compiled the Source and i can encrypt, decrypt, send and receive Messages :-)

**Comment by oopsmonk** [comment]
Designated initializer only support by gcc and clang.
https://gcc.gnu.org/onlinedocs/gcc/Designated-Inits.html

**Comment by H-saerdnA** [comment]
I have updated to Microsoft Visual C++ VS 2019.
Actually there is only one Probem compiling the code:

I have to change the initalisation of the arrays from:

  ` byte_t addr[ED25519_ADDRESS_BYTES] =` **{ }**`;`

to
 
   `byte_t addr[ED25519_ADDRESS_BYTES] =` **{ 0 }**`;`
   
   
An initialisation with ` {}` leads to an error.

I have tried some options in MSVC without success. Is it possible for you to change the initialisations ?

**Comment by oopsmonk** [comment]
> I have updated to Microsoft Visual C++ VS 2019.
> Actually there is only one Probem compiling the code:
> 
> I have to change the initalisation of the arrays from:
> 
> ` byte_t addr[ED25519_ADDRESS_BYTES] =` **{ }**`;`
> 
> to
> 
> `byte_t addr[ED25519_ADDRESS_BYTES] =` **{ 0 }**`;`
> 
> An initialisation with ` {}` leads to an error.
> 
> I have tried some options in MSVC without success. Is it possible for you to change the initialisations ?

Can you create a PR with regard to MSVC modifications? it's related to the compiler and should go with MSVS changes for a clear history.

**Comment by H-saerdnA** [comment]
Ok !
