### ISSUE TITLE
Core - transaction validation changes

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/iota.c#196]
Transaction validation
- [ ] Syntactic Validation
~- [ ] Semantic Validation~ it is performed by the node when its encapsulating message is confirmed by a milestone.

**Comment by matjazv** [comment]
Pay attention for Native Tokens, Feature blocks and Foundry outputs sorting:
- Native Tokens must be lexicographically sorted based on Token ID.
- Feature Blocks must be sorted in ascending order based on their Block Type.
- Foundry outputs must be sorted in the list of outputs based on their Serial Number.

When Native Tokens are added into a set by calling a function `native_tokens_add`, they are not sorted yet.

**Comment by oopsmonk** [comment]
blocked by #247

**Comment by oopsmonk** [comment]
Syntactic checks are implemented in corresponding objects
