### ISSUE TITLE
Running the IOTA.c library on ESP micro controllers

### ISSUE THREAD

**Issue by huggre** [iotaledger/iota.c#209]
Hi, would it be possible to run the IOTA.c library on microcontrollers such as the ESP8266 or ESP32?
If so, are there any tutorials as to how you compile and install the library on the controllers.
I'm working on a use case where I need to check the balance of a given IOTA address using an ESP based controller.
I'm familiar with the Arduino IDE and using existing Arduino libraries, but I'm not very familiar with C and C compilers in general.

**Comment by matjazv** [comment]
Hi huggre,
We have a separate repository for ESP32 microcontroller for iota.c library. You may find it here [https://github.com/iotaledger/esp32-client-sdk](https://github.com/iotaledger/esp32-client-sdk).
You will find a configuration and build instructions there.
If anything will still be unclear please let us know.
