### ISSUE TITLE
Feat - apply CERT coding standard

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/iota.c#222]
## Description

Source files should follow a coding standard for security concerns, therefore we should enable CERT checks in the GH action and fixes violations.

**Comment by matjazv** [comment]
To be able to read additional info on any violated rule and compliant solutions:
[CERT C Coding Standard Book](https://resources.sei.cmu.edu/downloads/secure-coding/assets/sei-cert-c-coding-standard-2016-v01.pdf)

**Comment by oopsmonk** [comment]
Since CMake 3.6 there is `<LANG>_CLANG_TIDY` to support clang-tidy. 
clang-tidy has its own checks and can also run Clang Static Analyzer checks.
To enable it in CMake, install clang-tidy and add the following line in CMakLists.txt 
```
set(CMAKE_C_CLANG_TIDY "clang-tidy;-checks=-*,cert-*,bugprone-*;")
```
the check list can be found at https://clang.llvm.org/extra/clang-tidy/checks/list.html

**Comment by matjazv** [comment]
CERT coding standard is publicly available but the tools which check if code is compliant to this standard are not. At least I can not find any open source tool. Cppcheck supports only very few rules from CERT coding standard so we can not use it as CERT coding standard validator.

In addition to `clang-tidy` Clang has another static analyzer called [scan-build](https://clang-analyzer.llvm.org/).
[CodeChecker](https://github.com/Ericsson/codechecker) is an analyzer tooling, defect database and viewer extension for the Clang Static Analyzer and Clang Tidy.

There exists also a great static analysis tool called [SonarLint](https://www.sonarlint.org/). It provides a plugin for VS Code and CLion.

[GCC 10](https://developers.redhat.com/blog/2020/03/26/static-analysis-in-gcc-10) and above also has built in static analyzer which may be used.

So we have quite some options to consider and improve static analysis of the library.
