### ISSUE TITLE
Core - message layout update

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/iota.c#318]
## Description

Message layout changes
- move `NetworkID` into transaction essence
- Add `Inputs Commitment` in the transaction essence
- Add `Protocol Version ` to the message

**Comment by matjazv** [comment]
NetworkID was changed to a string type.

**Comment by oopsmonk** [comment]
> NetworkID was changed to a string type.

Further explanation, NetworkID is an uint64_t in the Essence object but a string in a JSON Essence.
