### ISSUE TITLE
HTTP error on receiving chunked package.

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/iota.c#34]
## Bug description

HTTP client gets `Socket receive error` when handling header with `Transfer-Encoding: chunked`.

## Version

1.0.0-beta

## IOTA network

Which node are you connected to and which IOTA network is it in?

Hornet node.

## Hardware specification

Ubuntu laptop

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. connect to Hornet node
2. call `iota_client_get_trytes` API

## Expected behaviour

Get the response without errors.

## Errors

`cclient_core:    ERR: [iota_client_get_trytes:35] Socket receive error`

**Comment by HowJMay** [comment]
I am YangHau, engineer in BiiLabs. We met this same issue when we are developing our product tangle-accelerator. This problem prohibits us from connecting to Hornet. It's quite rush. Thanks for helping.

**Comment by kuhlmannmarkus** [comment]
Same problem for me.

**Comment by kuhlmannmarkus** [comment]
awesome, will test immediately
