### ISSUE TITLE
Core - Add unit tests for Shimmer coin type and its bech32 HRP

### ISSUE THREAD

**Issue by matjazv** [iotaledger/iota.c#386]
## Description

Add support for new Shimmer network in a Core and Client layer.

hrps: [Registered Shimmer coin_path](https://github.com/satoshilabs/slips/blob/master/slip-0173.md)
coin path: https://github.com/satoshilabs/slips/blob/master/slip-0044.md

Mainnet: `smr`
Testnet: `rms`

**Comment by oopsmonk** [comment]
examples for bech32 string validation can be found in [TIP-0031](https://github.com/iotaledger/tips/blob/add-smr-hrps/tips/TIP-0031/tip-0031.md)
