### ISSUE TITLE
Getting error "create transaction payload failed" while running wallet_send_tx.c application.

### ISSUE THREAD

**Issue by mahesh2392** [iotaledger/iota.c#458]
## Bug description
Getting error "create transaction payload failed" while running wallet_send_tx.c application from example directory because of " Err: input not found" as "outputIds":[] are missing .

## Version

Which version of the library are you running?
IOTA C client library
- Version: 0.0.2

## IOTA network
devnet
Which node are you connected to and which IOTA network is it in?

- Node URL:https://api.lb-0.h.chrysalis-devnet.iota.cafe/api/v1/addresses/ed25519/017ed3d67fc7b619e72e588f51fef2379e43e6e9a856635843b3f29aa3a3f1f0/outputs
- Network:devnet

## Hardware specification

What hardware are you using?

- Operating system: Linux ubuntu 20.04
- RAM: 32 GB
- Number of cores: 4
- Device type: PC
## Compiler and build tool specification

What compiler are you using?
 GCC 
What build tool are you using? 
Bazel/Bazelisk/CMake - CMake

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Build wallet application from example 
2. Run the application
3. 

## Expected behaviour

Describe what you expect to happen.
Successful tx and balance should add into wallet.

## Actual behaviour
failing while building payload itself

Describe what actually happens.
## Errors
[wallet_build_transaction:126 send_addr..... PZZӜ*B&R$th>/!K*\8WCX]
[wallet_build_transaction:135 tmp_addr..... 50A35A5AD39C899C2A42261F0687522474683E2F214BB32A5C38D10603574358]
[https address: api.lb-0.h.chrysalis-devnet.iota.cafe/api/v1/addresses/ed25519/50A35A5AD39C899C2A42261F0687522474683E2F214BB32A5C38D10603574358/outputs443]
[deser_outputs_from_address:124 res->u.output_ids->outputs 8]:
[res_outputs_address_output_id_count 70 res->u.output_ids->outputs =  0]
[wallet_build_transaction:155 out_counts... 0]
[wallet_build_transaction:187] Err: input not found
[wallet_build_transaction:218] Err: build tx failed
[wallet_send:384] Err: create transaction payload failed

**Comment by oopsmonk** [comment]
Hi @mahesh2392, the sender address has no outputs which means the balance is 0, so it cannot create a value transaction. please update the lib to v0.4.0 and request funds from the devnet faucet(https://faucet.chrysalis-devnet.iota.cafe/)

**Comment by mahesh2392** [comment]
Hi @oopsmonk , Thank you so much for quick reply and clarification as I am totally new for iota so having limited knowledge of it , as per your comments I am able to run wallet application. Thanks again!!!!
