### ISSUE TITLE
Error when trying to execute the send_basic_output example.

### ISSUE THREAD

**Issue by DerAnhalter** [iotaledger/iota.c#466]
## Bug description
When trying to execute the `send_basic_output` example, an error occurs in  `json_condition_expir_deserialize`:

the function `json_condition_expir_deserialize` expects a "milestoneIndex". But in the response to the request https://api.testnet.shimmer.network/api/core/v2/outputs/0x... there is no "milestoneIndex" and the function fails.

## Version

v1.0.1

## IOTA network

- Node URL: https://api.testnet.shimmer.network

## Hardware specification

- Operating system: Windows

## Compiler and build tool specification

Microsoft Visual Studio Community 2022 

## Errors

`[json_get_uint32:438] JSON key not found: milestoneIndex`

**Comment by oopsmonk** [comment]
the problem with sending basic outputs is remote PoW is not enabled on the shimmer testnet.
you can spin up a private tangle to test the `send_basic_output` example.

```
Sender address: tst1qzgmsrsf94544n4zwhj3nee9s4ej4zdr5s68u4jgkc5rx5l74acu56l3jd8
Receiver address: tst1qrtn3fjyjhdyspkdzy3nudc5l59sshdtlynl3rzwmc3mud23np6ugxc5xwp
Amount to send: 1000000

Sending transaction block to the Tangle...
Block successfully sent.
Block ID: b35905eb00daf3ed276d233361fe6b9117a136168255372bacfcbf18e0fa076a
```

the root cause of `json_condition_expir_deserialize` is the JSON object of the expiration condition has been changed but it won't cause the `send_basic_output` example to fail.

**Comment by DerAnhalter** [comment]
My Node is working fine on the shimmer testnet. I have enabled pow on the Node. This shows a transaction with send_basic_output and the mnemonic string as defined in the example.

```
Sender address: rms1qq7xx9h4snrmxzyd3k40cu5ppu23c9c39at6f20ar3vrz5w5e8mfj8gavke
Receiver address: rms1qpakdmts2xep5ez8y5rgqtstaqddtxy2r7gndkvh2rckycsgl29tjzdsusk
Amount to send: 1000000

Sending transaction block to the Tangle...
Block successfully sent.
Block ID: b5d3054e9c582089eee1066342190248b06cfe4c0cd53a8ada4b6f06cd1cb378
```

Now i use the same Code but an other mnemonic string. Then I get the Error:
```
Sending transaction block to the Tangle...
[json_get_uint32:438] JSON key not found: milestoneIndex
[json_condition_expir_deserialize:248]: getting milestoneIndex json uint32 failed
```

I found out that the error occurs during the deserialization of the request response:

`.../api/core/v2/outputs/0xc610896581070d8c62d66c3df2300ea497eba997b285bc8d92b073ee716042a00700`

`...{"type":3,"returnAddress":{"type":0,"pubKeyHash":"0x8297ac4149c80cca8225e5f2da36df89a93cd2998d7f6d488c97250a881e65af"},"unixTime":1659436402}...`

The function json_condition_expir_deserialize expects a "milestoneIndex" but ther is no one.
