### ISSUE TITLE
Crypto - slip10 key derivation methods.

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/iota.c#54]
implements [slip-10](https://github.com/satoshilabs/slips/blob/master/slip-0010.md) functionaty using crypto abstruction layer.

**Comment by bernardoaraujor** [comment]
maybe useful? 
https://github.com/ElementsProject/libwally-core/blob/master/src/bip38.c
https://github.com/ElementsProject/libwally-core/blob/master/src/bip32.c

![68747470733a2f2f77696b692e7472657a6f722e696f2f696d616765732f44657269766174696f6e2e706e67](https://user-images.githubusercontent.com/9698228/99698511-2a1b7880-2a91-11eb-8509-e62dda81b578.png)

**Comment by oopsmonk** [comment]
> maybe useful?
> https://github.com/ElementsProject/libwally-core/blob/master/src/bip38.c
> https://github.com/ElementsProject/libwally-core/blob/master/src/bip32.c
> 

do you mean use libwally-core? it bundled with unnecessary components, considering portability it's not fit to iota.c
