### ISSUE TITLE
unchecked error on get_node_info

### ISSUE THREAD

**Issue by bernardoaraujor** [iotaledger/iota.c#57]
after enabling `RUN_TEST(test_get_info)` on `test_get_info.c`: https://github.com/iotaledger/iota.c/blob/0a0552a1fdf9a86852ae21df0a1200ca7a17a5f8/tests/client/api_v1/test_get_info.c#L38

I found that cURL is returning error that goes unchecked during `http_client_get()`:
https://github.com/iotaledger/iota.c/blob/0a0552a1fdf9a86852ae21df0a1200ca7a17a5f8/src/client/api/v1/get_node_info.c#L40

**Comment by oopsmonk** [comment]
A valid endpoint is needed, it's for local test only since we don't have an official endpoint yet.
https://github.com/iotaledger/iota.c/blob/82598d9a8a958f98895cf2d35dfc8b3f951e4329/tests/client/api_v1/test_get_info.c#L8

**Comment by bernardoaraujor** [comment]
You can deploy endpoint locally.

Assuming you have [Golang 1.15](https://tecadmin.net/install-go-on-ubuntu/):
```
$ git clone https://github.com/gohornet/hornet
$ cd hornet
$ git checkout chrysalis-pt2
$ ./run_coo_bootstrap.sh
```

**Comment by oopsmonk** [comment]
chrysalis-pt 2 is in a highly developed peace, I won't recommend you deploy node by yourself, please refer to [Node API RFC](https://github.com/iotaledger/protocol-rfcs/pull/27). 

btw, there's no problem from my side
```
$ ./tests/client_get_info
../tests/client/api_v1/test_get_info.c:37:test_deser_node_info:PASS
../tests/client/api_v1/test_get_info.c:38:test_get_info:PASS
```

**Comment by bernardoaraujor** [comment]
in order to reproduce issue, please point to invalid endpoint.

**Comment by oopsmonk** [comment]
I see, I thought you were referring to the failure of the get_node_info test case.
Some fields are missing in deser_node_info as well that need to revisit, welcome to submit a PR.

**Comment by bernardoaraujor** [comment]
to be solved via https://github.com/iotaledger/iota.c/issues/62
closing.
