### ISSUE TITLE
problem with IOTA_ADDRESS_BYTES define

### ISSUE THREAD

**Issue by bernardoaraujor** [iotaledger/iota.c#59]
`IOTA_ADDRESS_BYTES`[ is defined as 33 bytes](https://github.com/iotaledger/iota.c/blob/82598d9a8a958f98895cf2d35dfc8b3f951e4329/src/core/address.h#L11
), which is correct only for Ed25519.

W-OTS address has[50 bytes when serialized](https://github.com/Wollac/protocol-rfcs/blob/bech32-address-format/text/0020-bech32-address-format/0020-bech32-address-format.md#examples).

I propose renaming `IOTA_ADDRESS_BYTES` to `IOTA_ADDR_ED_LEN`, and introducing a new `IOTA_ADDR_WOTS_LEN`.

**Comment by oopsmonk** [comment]
W-OTS address and signature scheme are not supported in iota.c.

**Comment by bernardoaraujor** [comment]
ah ok that explains a lot!
I'm also relieved because now there's 50% less work to do! 
😂😂😂
