### ISSUE TITLE
API - get node info

### ISSUE THREAD

**Issue by bernardoaraujor** [iotaledger/iota.c#62]
## Description

Communicates with node API: `GET /api/v1/info`

http status code 200:
```
{
  "data": {
    "name": "HORNET",
    "version": "0.5.3",
    "isHealthy": false,
    "networkId": "alphanet1",
    "latestMilestoneIndex": 106264,
    "solidMilestoneIndex": 106264,
    "pruningIndex": 0,
    "features": [
      "PoW"
    ]
  }
}
```

## Motivation

Get node info via HTTP API.

## Requirements

1. parses JSON
2. returns populated `res_node_info_t`

## Are you planning to do it yourself in a pull request?

Yes

**Comment by bernardoaraujor** [comment]
@oopsmonk please assign to me.

**Comment by oopsmonk** [comment]
> @oopsmonk please assign to me.

I believe you can assign it to yourself. please inform me if something wrong.
