### ISSUE TITLE
Failed C++ build.

### ISSUE THREAD

**Issue by SiliconDroid** [iotaledger/iota.c#75]
Compiled using PlatformIO C++ for ESP32: toolchain: xtensa32 2.50200.80

I got a conflicting declaration linker error.

I got a good build by removing the declaration of dump_hex() from address.h.

Build Error:
.pio/libdeps/ttgo-t-watch/iota_client/src/core/address.h:64:47: error: conflicting declaration of 'void dump_hex(const byte_t*, size_t)' with 'C' linkage
void dump_hex(byte_t const data[], size_t len);
^
In file included from .pio/libdeps/ttgo-t-watch/iota_client/src/client/api/v1/get_health.h:11:0,
from src\SD_Object_Iota.h:15,
from src\SD_Main.h:24,
from src\SD_Object_FrameTimer.cpp:9:
.pio/libdeps/ttgo-t-watch/iota_client/src/core/types.h:21:20: note: previous declaration with 'C++' linkage
static inline void dump_hex(byte_t const data[], size_t len)

**Comment by oopsmonk** [comment]
@SiliconDroid esp-idf support for Chrysalis is not done yet on `dev` branch and network layer is not working for esp-idf.

**Comment by SiliconDroid** [comment]
OK, no worries, It looks like net layer should work for esp-idf after removing declarations for http_client_post and http_client_get from http.h.

esp_http_client.h (arduinoespressif32\tools\sdk\include\esp_http_client\esp_http_client.h) 
gets included and called from your code: http_esp32.c code.

Anyway it's cool to see that ESP-IDF compatibility is being worked in, great work from all you guys!

**Comment by oopsmonk** [comment]
> OK, no worries, It looks like net layer should work for esp-idf after removing declarations for http_client_post and http_client_get from http.h.

yes, the net layer is an abstraction, if you have other http client implementations just ignore it.
the core layer(`src/core`) will be refactored in the following weeks.

> esp_http_client.h (arduinoespressif32\tools\sdk\include\esp_http_client\esp_http_client.h)
> gets included and called from your code: http_esp32.c code.
> 
> Anyway it's cool to see that ESP-IDF compatibility is being worked in, great work from all you guys!

here are PoCs using esp-idf but it's not the Chrysalis spec:
https://github.com/oopsmonk/tangle_pigeon_esp32
https://github.com/oopsmonk/iota_esp32_cashier
https://github.com/oopsmonk/iota_esp32_wallet

**Comment by oopsmonk** [comment]
@SiliconDroid I closed this issue since iota.c has been tested on PlatfromIO with espidf framework, you can find the example here: https://github.com/oopsmonk/iota_c_platformIO/tree/dev_esp32_chrysalis
