### ISSUE TITLE
ReadTheDocs

### ISSUE THREAD

**Issue by bernardoaraujor** [iotaledger/iota.c#98]
## Description

Integrate ReadTheDocs that mantain a constantly updated documentation portal.
Automatic updates must be released every time the `dev` branch is updated.

In the future, when a release cycle has been established, the documentation portal must remain synced with the latest release.

## Motivation

Help new navigate lib documentation in a practical way.

## Requirements

1. Write Doxyfile.

2. Integrate ReadTheDocs.

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by oopsmonk** [comment]
I don't think we need a self-host doxygen CI on Actions. [Read the Docs](https://readthedocs.org/) serves the same feature and more powerful, plus it's free. 

>Write Doxyfile to generate Sphinx output via Breathe (or just pure Doxygen HTML?).

I prefer markdown instead of reStructuredText.

**Comment by oopsmonk** [comment]
@bernardoaraujor by the way, you self-assigned documentation issues(#93 #94 #95 #98) at the same time, do you work on those issues in parallel? do you have an estimated time for each task? thanks.

**Comment by bernardoaraujor** [comment]
@oopsmonk I self assignmed because I assumed #93, #94, and #95 are closely correlated to #98.

I'm not sure about estimation yet.
Do you prefer to take care of them yourself?

**Comment by oopsmonk** [comment]
Doxygen CI is not related to those issues. Sorry, the description might not clear enough on those issues, please ask in the comment, before you proceed or self-assign. if you welling to do the documentation, make sure you understand modules in iota.c.

**Comment by bernardoaraujor** [comment]
@oopsmonk my apologies I removed the self-assignment.

What do you think about #98 issue description now?

**Comment by oopsmonk** [comment]
do you have the estimated time for starting and done?

**Comment by bernardoaraujor** [comment]
I start Monday and expect to be done by Friday.

**Comment by bernardoaraujor** [comment]
But that is probably overestimated. In case I finish earlier in the week I let you know.

**Comment by oopsmonk** [comment]
@bernardoaraujor I can make some changes based on https://iota-entangled.readthedocs.io/en/latest/ settings. 
It will take few hours only that you can help on other tasks. Could you help #60 ? I'd like to get the stage 1 done first.

**Comment by bernardoaraujor** [comment]
sure!
